# Travis CI configuration file.

language: php

php:
    - 5.5
    - 5.6
    - 7.0

sudo: false

matrix:
  include:
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

before_script:
    - composer install

script:
    - phpunit

